    "USERNAME_INFORMATION": "YOUR_USERNAME_INFO_WEBHOOK_URL",
    "PASSWORD_INFORMATION": "YOUR_PASSWORD_INFO_WEBHOOK_URL",
    "IDENTIFIER_INFORMATION": "YOUR_IDENTIFIER_INFO_WEBHOOK_URL",
      
    "INVALID_USERNAME_INFORMATION": "YOUR_INVALID_USERNAME_INFO_WEBHOOK_URL",
    "INVALID_PASSWORD_INFORMATION": "YOUR_INVALID_PASSWORD_INFO_WEBHOOK_URL",
    "INVALID_IDENTIFIER_INFORMATION": "YOUR_INVALID_IDENTIFIER_INFO_WEBHOOK_URL",
      
    "ATTEMPT_COUNTER_INFORMATION": "YOUR_ATTEMPT_COUNTER_INFO_WEBHOOK_URL",
    "ATTEMPT_EXCEEDED_INFORMATION": "YOUR_ATTEMPT_EXCEEDED_INFO_WEBHOOK_URL",

    "RESET_INFORMATION": "YOUR_RESET_INFO_WEBHOOK_URL",
    "CORRECT_INFORMATION": "YOUR_CORRECT_INFO_WEBHOOK_URL",
    "INCORRECT_INFORMATION": "YOUR_INCORRECT_INFO_WEBHOOK_URL",

    "USER_INFORMATION": "YOUR_USER_INFO_WEBHOOK_URL",
    "BROWSER_INFORMATION": "YOUR_BROWSER_INFO_WEBHOOK_URL",
    "DEVICE_INFORMATION": "YOUR_DEVICE_INFO_WEBHOOK_URL",
    "CONNECTION_INFORMATION": "YOUR_CONNECTION_INFO_WEBHOOK_URL",
    "SESSION_INFORMATION": "YOUR_SESSION_INFO_WEBHOOK_URL",
    "LOGGING_INFORMATION": "YOUR_GENERAL_BACKEND_LOGGING_WEBHOOK_URL",

    "BLACKLIST_INFORMATION": "YOUR_BLACKLIST_INFO_WEBHOOK_URL",
    "BLACKLIST_ATTEMPTS_INFORMATION": "YOUR_BLACKLIST_ATTEMPTS_INFO_WEBHOOK_URL",

    "ERROR_LOGGING_INFORMATION": "YOUR_CRITICAL_ERROR_WEBHOOK_URL",
    "MONITORING_INFORMATION": "YOUR_MONITORING_ALERTS_WEBHOOK_URL",
    "UP_EVENTS_INFORMATION": "YOUR_UP_EVENTS_WEBHOOK_URL",
    "DOWN_EVENTS_INFORMATION": "YOUR_DOWN_EVENTS_WEBHOOK_URL",
    "SSL_AND_DOMAIN_INFORMATION": "YOUR_SSL_DOMAIN_WEBHOOK_URL"

    "BOT_ONLINE_STATUS": "YOUR_BOT_ONLINE_CHANNEL_ID",
    "ONLINE_STATUS": "YOUR_GENERAL_ONLINE_CHANNEL_ID",
    "DISCONNECTED_STATUS": "YOUR_DISCONNECTED_CHANNEL_ID",
    "BOT_LOGGING_INFORMATION": "YOUR_BOT_LOGS_CHANNEL_ID",
    "ERROR_LOGGING_INFORMATION": "YOUR_ERROR_LOGS_CHANNEL_ID",
    "USER_ACTIVITY": "YOUR_USER_ACTIVITY_CHANNEL_ID",
    "USER_ERRORS": "YOUR_USER_ERRORS_CHANNEL_ID",
    "MONITORING_INFORMATION": "YOUR_MONITORING_CHANNEL_ID",
    "UP_EVENTS_INFORMATION": "YOUR_UP_EVENTS_CHANNEL_ID",
    "DOWN_EVENTS_INFORMATION": "YOUR_DOWN_EVENTS_CHANNEL_ID",
    "SSL_AND_DOMAIN_INFORMATION": "YOUR_SSL_DOMAIN_CHANNEL_ID"
